-- Base projects table: one row per event/project; owned by creator (user_id).
-- Required by: project_photos, project_share_links, event_access, user_albums.
create table if not exists public.projects (
  id bigint primary key generated by default as identity,
  user_id uuid not null references auth.users(id) on delete cascade,
  project_name text,
  project_date text,
  client_name text,
  cover_url text,
  created_at timestamptz not null default now()
);

create index if not exists idx_projects_user_id on public.projects(user_id);
create index if not exists idx_projects_created_at on public.projects(created_at desc);

alter table public.projects enable row level security;

-- Project owners can manage their own projects (select, insert, update, delete).
create policy "Project owners can manage own projects"
  on public.projects for all
  using (user_id = auth.uid())
  with check (user_id = auth.uid());
